from typing import List
from models.schemas import KeywordCreate

def get_initial_keywords() -> List[KeywordCreate]:
    """
    Returns a list of 100+ domain-specific keywords for MHP Management- und IT-Beratung.
    Demonstrates 3-level hierarchy: Type -> Sub-type -> Sub-category
    """
    
    # 1. SECTORS (BRANCHEN)
    sectors = [
        ('AI', 2.0, 'Aerospace & Defense', 'Automation', 'Aerospace & Defense'),
        ('Acquisitions', 2.0, 'Aerospace & Defense', 'M&A', 'Aerospace & Defense'),
        ('Automated', 2.0, 'Aerospace & Defense', 'Automation', 'Aerospace & Defense'),
        ('Chain', 2.0, 'Aerospace & Defense', 'Logistics', 'Aerospace & Defense'),
        ('Cybersecurity', 2.0, 'Aerospace & Defense', 'Digital Defense', 'Aerospace & Defense'),
        ('Defense', 2.0, 'Aerospace & Defense', 'Digital Defense', 'Aerospace & Defense'),
        ('Digital', 2.0, 'Aerospace & Defense', 'Digital Defense', 'Aerospace & Defense'),
        ('Diversification', 2.0, 'Aerospace & Defense', 'Aviation Strategy', 'Aerospace & Defense'),
        ('Generation', 2.0, 'Aerospace & Defense', 'Innovation', 'Aerospace & Defense'),
        ('Mergers', 2.0, 'Aerospace & Defense', 'M&A', 'Aerospace & Defense'),
        ('Next', 2.0, 'Aerospace & Defense', 'Innovation', 'Aerospace & Defense'),
        ('Operations', 2.0, 'Aerospace & Defense', 'Drones', 'Aerospace & Defense'),
        ('Resilience', 2.0, 'Aerospace & Defense', 'Logistics', 'Aerospace & Defense'),
        ('Shopfloor', 2.0, 'Aerospace & Defense', 'Agile Production', 'Aerospace & Defense'),
        ('Smart', 2.0, 'Aerospace & Defense', 'Agile Production', 'Aerospace & Defense'),
        ('Supply', 2.0, 'Aerospace & Defense', 'Logistics', 'Aerospace & Defense'),
        ('Systems', 2.0, 'Aerospace & Defense', 'Automation', 'Aerospace & Defense'),
        ('Unmanned', 2.0, 'Aerospace & Defense', 'Drones', 'Aerospace & Defense'),
        ('Automotive', 2.0, 'Automotive', 'General', 'Automotive'),
        ('Autonomes', 2.0, 'Automotive', 'Autonomous Driving', 'Automotive'),
        ('Car', 1.5, 'Automotive', 'Connectivity', 'Automotive'),
        ('Car', 2.0, 'Automotive', 'Connectivity', 'Automotive'),
        ('Connected', 2.0, 'Automotive', 'Connectivity', 'Automotive'),
        ('Connected', 1.5, 'Automotive', 'Connectivity', 'Automotive'),
        ('Defined', 2.0, 'Automotive', 'SDV', 'Automotive'),
        ('Digital', 2.0, 'Automotive', 'Digital Service', 'Automotive'),
        ('Elektromobilität', 2.0, 'Automotive', 'E-Mobility', 'Automotive'),
        ('Fahren', 2.0, 'Automotive', 'Autonomous Driving', 'Automotive'),
        ('Fahrzeugbau', 2.0, 'Automotive', 'General', 'Automotive'),
        ('Flexible', 1.5, 'Automotive', 'Flexibility', 'Automotive'),
        ('Flottenmanagement', 2.0, 'Automotive', 'Mobility Services', 'Automotive'),
        ('Mobility', 2.0, 'Automotive', 'Sustainability', 'Automotive'),
        ('Mobility', 2.0, 'Automotive', 'E-Mobility', 'Automotive'),
        ('Mobilitätsdienstleistung', 2.0, 'Automotive', 'Mobility Services', 'Automotive'),
        ('OEM', 2.0, 'Automotive', 'General', 'Automotive'),
        ('SDV', 2.0, 'Automotive', 'Software Defined Vehicle', 'Automotive'),
        ('Software', 2.0, 'Automotive', 'SDV', 'Automotive'),
        ('Sustainable', 2.0, 'Automotive', 'Sustainability', 'Automotive'),
        ('Vehicle', 2.0, 'Automotive', 'SDV', 'Automotive'),
        ('Zulieferer', 2.0, 'Automotive', 'General', 'Automotive'),
        ('AI', 2.0, 'Logistics & Transportation', 'AI', 'Logistics & Transportation'),
        ('Automation', 2.0, 'Logistics & Transportation', 'Automation', 'Logistics & Transportation'),
        ('Big', 1.5, 'Logistics & Transportation', 'Data Analytics', 'Logistics & Transportation'),
        ('Blockchain', 1.5, 'Logistics & Transportation', 'Transparency', 'Logistics & Transportation'),
        ('Cloud', 1.5, 'Logistics & Transportation', 'Cloud', 'Logistics & Transportation'),
        ('Computing', 1.5, 'Logistics & Transportation', 'Cloud', 'Logistics & Transportation'),
        ('Cost', 1.5, 'Logistics & Transportation', 'Efficiency', 'Logistics & Transportation'),
        ('Customer', 1.5, 'Logistics & Transportation', 'CX', 'Logistics & Transportation'),
        ('Data', 1.5, 'Logistics & Transportation', 'Data Analytics', 'Logistics & Transportation'),
        ('End', 1.5, 'Logistics & Transportation', 'E2E', 'Logistics & Transportation'),
        ('Experience', 1.5, 'Logistics & Transportation', 'CX', 'Logistics & Transportation'),
        ('Fleet', 1.5, 'Logistics & Transportation', 'Fleet', 'Logistics & Transportation'),
        ('IoT', 1.5, 'Logistics & Transportation', 'IoT', 'Logistics & Transportation'),
        ('Logistics', 2.0, 'Logistics & Transportation', 'Digitalization', 'Logistics & Transportation'),
        ('Management', 1.5, 'Logistics & Transportation', 'Fleet', 'Logistics & Transportation'),
        ('Optimization', 1.5, 'Logistics & Transportation', 'Efficiency', 'Logistics & Transportation'),
        ('Sustainability', 2.0, 'Logistics & Transportation', 'Green Logistics', 'Logistics & Transportation'),
        ('Warehouse', 2.0, 'Logistics & Transportation', 'Automation', 'Logistics & Transportation'),
        ('Analyse', 2.0, 'Management & Strategy', 'Methods', 'Research'),
        ('Benchmarking', 2.0, 'Management & Strategy', 'Strategy', 'MarketAnalysis'),
        ('Beratung', 2.0, 'Management & Strategy', 'Service', 'Consulting'),
        ('Change', 2.0, 'Management & Strategy', 'Transformation', 'ChangeSupport'),
        ('Einzel', 2.0, 'Management & Strategy', 'Context', 'Coaching'),
        ('Einzelcoaching', 2.0, 'Management & Strategy', 'Leadership', 'CoachingServices'),
        ('Erstellung', 2.0, 'Management & Strategy', 'Methods', 'Documentation'),
        ('Führung', 2.0, 'Management & Strategy', 'Leadership', 'Coaching'),
        ('Führungskräfte', 2.0, 'Management & Strategy', 'Leadership', 'ExecutiveConsulting'),
        ('Führungskultur', 2.0, 'Management & Strategy', 'Leadership', 'CultureChange'),
        ('Geschäftsmodell', 2.0, 'Management & Strategy', 'Strategy', 'Innovation'),
        ('Gruppe', 2.0, 'Management & Strategy', 'Context', 'Coaching'),
        ('Gruppencoaching', 2.0, 'Management & Strategy', 'Leadership', 'TeamDevelopment'),
        ('Interim', 2.0, 'Management & Strategy', 'Management', 'TemporaryLeadership'),
        ('Kultur', 2.0, 'Management & Strategy', 'Culture', 'OrganizationalHealth'),
        ('Kulturwandel', 2.0, 'Management & Strategy', 'Transformation', 'CultureChange'),
        ('Management', 2.0, 'Management & Strategy', 'Management', 'Advisory'),
        ('Managementberatung', 2.0, 'Management & Strategy', 'Strategy', 'BusinessStrategy'),
        ('Organisationsberatung', 2.0, 'Management & Strategy', 'Organization', 'OrgDesign'),
        ('Organisationsdesign', 2.0, 'Management & Strategy', 'Organization', 'OrgDesign'),
        ('Personalentwicklung', 2.0, 'Management & Strategy', 'HRStrategy', 'TalentManagement'),
        ('Prozessoptimierung', 2.0, 'Management & Strategy', 'Efficiency', 'Lean'),
        ('Roadmap', 2.0, 'Management & Strategy', 'Planning', 'StrategicPlanning'),
        ('Stakeholder', 2.0, 'Management & Strategy', 'Communication', 'StakeholderMgmt'),
        ('Strategie', 2.0, 'Management & Strategy', 'Strategy', 'Advisory'),
        ('Unternehmensberatung', 2.0, 'Management & Strategy', 'Strategy', 'BusinessStrategy'),
        ('Wissen', 2.0, 'Management & Strategy', 'Organization', 'KnowledgeMgmt'),
        ('Zielbild', 2.0, 'Management & Strategy', 'Strategy', 'VisionSetting'),
        ('40', 2.0, 'Manufacturing', 'Smart Factory', 'Manufacturing'),
        ('Centricity', 1.5, 'Manufacturing', 'CX', 'Manufacturing'),
        ('Chain', 2.0, 'Manufacturing', 'Supply Chain', 'Manufacturing'),
        ('Creation', 1.5, 'Manufacturing', 'R&D', 'Manufacturing'),
        ('Digital', 2.0, 'Manufacturing', 'Digital Factory', 'Manufacturing'),
        ('Digital', 2.0, 'Manufacturing', 'Virtualization', 'Manufacturing'),
        ('Excellence', 1.5, 'Manufacturing', 'Sales & Service', 'Manufacturing'),
        ('Factory', 2.0, 'Manufacturing', 'Smart Factory', 'Manufacturing'),
        ('Fertigung', 2.0, 'Manufacturing', 'General', 'Manufacturing'),
        ('Future', 2.0, 'Manufacturing', 'Smart Factory', 'Manufacturing'),
        ('Industrie', 2.0, 'Manufacturing', 'Smart Factory', 'Manufacturing'),
        ('IoT', 2.0, 'Manufacturing', 'IoT', 'Manufacturing'),
        ('Lieferkette', 2.0, 'Manufacturing', 'Supply Chain', 'Manufacturing'),
        ('Logistik', 2.0, 'Manufacturing', 'Logistics', 'Manufacturing'),
        ('Manufacturing', 2.0, 'Manufacturing', 'General', 'Manufacturing'),
        ('Product', 1.5, 'Manufacturing', 'R&D', 'Manufacturing'),
        ('Produktion', 2.0, 'Manufacturing', 'General', 'Manufacturing'),
        ('Service', 1.5, 'Manufacturing', 'Sales & Service', 'Manufacturing'),
        ('Smart', 2.0, 'Manufacturing', 'Smart Factory', 'Manufacturing'),
        ('Supply', 2.0, 'Manufacturing', 'Supply Chain', 'Manufacturing'),
        ('Twin', 2.0, 'Manufacturing', 'Digital Factory', 'Manufacturing'),
        ('Twins', 2.0, 'Manufacturing', 'Virtualization', 'Manufacturing'),
        ('Behörde', 2.0, 'Public Sector', 'General', 'Public Sector'),
        ('Cyber', 2.0, 'Public Sector', 'Security', 'Public Sector'),
        ('Dienst', 2.0, 'Public Sector', 'General', 'Public Sector'),
        ('Digitalisierung', 2.0, 'Public Sector', 'E-Government', 'Public Sector'),
        ('Government', 2.0, 'Public Sector', 'E-Government', 'Public Sector'),
        ('Integration', 2.0, 'Public Sector', 'Integration', 'Public Sector'),
        ('OZG', 2.0, 'Public Sector', 'E-Government', 'Public Sector'),
        ('Organizational', 2.0, 'Public Sector', 'Org Transformation', 'Public Sector'),
        ('Public', 2.0, 'Public Sector', 'General', 'Public Sector'),
        ('SAP', 2.0, 'Public Sector', 'SAP', 'Public Sector'),
        ('Sector', 2.0, 'Public Sector', 'General', 'Public Sector'),
        ('Security', 2.0, 'Public Sector', 'Security', 'Public Sector'),
        ('System', 2.0, 'Public Sector', 'Integration', 'Public Sector'),
        ('Transformation', 2.0, 'Public Sector', 'Cloud', 'Public Sector'),
        ('Verwaltung', 2.0, 'Public Sector', 'General', 'Public Sector'),
        ('Verwaltung', 2.0, 'Public Sector', 'E-Government', 'Public Sector'),
        ('Öffentlicher', 2.0, 'Public Sector', 'General', 'Public Sector'),
    ]

    # 2. SERVICES (LEISTUNGEN)
    services = [
        ('AI4Human', 2.0, 'Artificial Intelligence', 'AI4Human'),
        ('Enablement', 2.0, 'Artificial Intelligence', 'Organisational Enablement'),
        ('Organisational', 2.0, 'Artificial Intelligence', 'Organisational Enablement'),
        ('Platform', 2.0, 'Artificial Intelligence', 'Platform & Technology'),
        ('Technology', 2.0, 'Artificial Intelligence', 'Platform & Technology'),
        ('Customer', 2.0, 'Business Process Outsourcing', 'Digital Customer Services'),
        ('Digital', 2.0, 'Business Process Outsourcing', 'Digital Customer Services'),
        ('Digitalization', 2.0, 'Business Process Outsourcing', 'Digitalization'),
        ('Expertise', 2.0, 'Business Process Outsourcing', 'Expertise'),
        ('Fulfillment', 2.0, 'Business Process Outsourcing', 'Outsourcing Fulfillment'),
        ('Highest', 2.0, 'Business Process Outsourcing', 'Expertise'),
        ('Level', 2.0, 'Business Process Outsourcing', 'Expertise'),
        ('Outsourcing', 2.0, 'Business Process Outsourcing', 'Outsourcing Strategy'),
        ('Services', 2.0, 'Business Process Outsourcing', 'Digital Customer Services'),
        ('Strategy', 2.0, 'Business Process Outsourcing', 'Outsourcing Strategy'),
        ('Advisory', 2.0, 'CIO Advisory', 'M&A Advisory'),
        ('Architecture', 2.0, 'CIO Advisory', 'Digital Architecture'),
        ('Communication', 2.0, 'CIO Advisory', 'Communication'),
        ('Enabling', 2.0, 'CIO Advisory', 'Communication'),
        ('M&A', 2.0, 'CIO Advisory', 'M&A Advisory'),
        ('Model', 2.0, 'CIO Advisory', 'Target Operating Model'),
        ('Operating', 2.0, 'CIO Advisory', 'Target Operating Model'),
        ('Target', 2.0, 'CIO Advisory', 'Target Operating Model'),
        ('Workplace', 2.0, 'CIO Advisory', 'Digital Workplace'),
        ('Cloud', 2.0, 'Cloud Transformation', 'Cloud Strategy'),
        ('Development', 2.0, 'Cloud Transformation', 'Cloud Development'),
        ('Migration', 2.0, 'Cloud Transformation', 'Cloud Migration'),
        ('Operation', 2.0, 'Cloud Transformation', 'Cloud Operation'),
        ('Business', 2.0, 'Customer Experience', 'Digital Business Models'),
        ('Centricity', 2.0, 'Customer Experience', 'Customer Centricity'),
        ('Commerce', 2.0, 'Customer Experience', 'Fascinating Commerce'),
        ('Fascinating', 2.0, 'Customer Experience', 'Fascinating Commerce'),
        ('Maintenance', 2.0, 'Customer Experience', 'Smart Maintenance Systems'),
        ('Models', 2.0, 'Customer Experience', 'Digital Business Models'),
        ('Access', 2.0, 'Cyber Security', 'IAM'),
        ('Application', 2.0, 'Cyber Security', 'Application Security'),
        ('Identity', 2.0, 'Cyber Security', 'IAM'),
        ('Industrial', 2.0, 'Cyber Security', 'OT/IoT'),
        ('Infrastructure', 2.0, 'Cyber Security', 'Infrastructure Security'),
        ('Risk', 2.0, 'Cyber Security', 'Risk Management'),
        ('Advanced', 2.0, 'Data Analytics', 'Data Science'),
        ('Analytics', 2.0, 'Data Analytics', 'Data Science'),
        ('Engineering', 2.0, 'Data Analytics', 'Data Engineering'),
        ('Governance', 2.0, 'Data Analytics', 'Data Strategy'),
        ('Intelligence', 2.0, 'Data Analytics', 'BI'),
        ('Science', 2.0, 'Data Analytics', 'Data Science'),
        ('AI', 2.0, 'Digital Product & Data', 'AI'),
        ('API', 2.0, 'Digital Product & Data', 'Engineering'),
        ('Algorithm', 2.0, 'Digital Product & Data', 'AI'),
        ('Analytics', 2.0, 'Digital Product & Data', 'AI'),
        ('Backend', 2.0, 'Digital Product & Data', 'Engineering'),
        ('Dashboard', 2.0, 'Digital Product & Data', 'Data'),
        ('Data', 2.0, 'Digital Product & Data', 'AI'),
        ('Digital', 2.0, 'Digital Product & Data', 'Transformation'),
        ('Docker', 2.0, 'Digital Product & Data', 'Engineering'),
        ('Experience', 2.0, 'Digital Product & Data', 'Product'),
        ('Frontend', 2.0, 'Digital Product & Data', 'Engineering'),
        ('Generative', 2.0, 'Digital Product & Data', 'AI'),
        ('Intelligenz', 2.0, 'Digital Product & Data', 'AI'),
        ('KI', 2.0, 'Digital Product & Data', 'AI'),
        ('Kubernetes', 2.0, 'Digital Product & Data', 'Engineering'),
        ('Künstliche', 2.0, 'Digital Product & Data', 'AI'),
        ('Learning', 2.0, 'Digital Product & Data', 'AI'),
        ('MVP', 2.0, 'Digital Product & Data', 'Product'),
        ('Machine', 2.0, 'Digital Product & Data', 'AI'),
        ('Predictive', 2.0, 'Digital Product & Data', 'AI'),
        ('Quality', 2.0, 'Digital Product & Data', 'Data'),
        ('Research', 2.0, 'Digital Product & Data', 'Product'),
        ('Science', 2.0, 'Digital Product & Data', 'AI'),
        ('Twin', 2.0, 'Digital Product & Data', 'Innovation'),
        ('UI', 2.0, 'Digital Product & Data', 'Product'),
        ('API', 2.0, 'Digital Services', 'Architecture'),
        ('AWS', 2.0, 'Digital Services', 'Cloud Platforms'),
        ('Azure', 2.0, 'Digital Services', 'Cloud Platforms'),
        ('Cloud', 2.0, 'Digital Services', 'Cloud Architecture'),
        ('Cloud', 2.0, 'Digital Services', 'Cloud Computing'),
        ('Cloud', 2.0, 'Digital Services', 'Cloud Platforms'),
        ('Cloud', 2.0, 'Digital Services', 'Migration'),
        ('Design', 2.0, 'Digital Services', 'Service Design'),
        ('DevOps', 2.0, 'Digital Services', 'Development'),
        ('Economy', 2.0, 'Digital Services', 'Platform Economy'),
        ('Google', 2.0, 'Digital Services', 'Cloud Platforms'),
        ('Hybrid', 2.0, 'Digital Services', 'Cloud Architecture'),
        ('Java', 2.0, 'Digital Services', 'Development'),
        ('Management', 2.0, 'Digital Services', 'Architecture'),
        ('Microservices', 2.0, 'Digital Services', 'Architecture'),
        ('Migration', 2.0, 'Digital Services', 'Migration'),
        ('Product', 2.0, 'Digital Services', 'Product Development'),
        ('Python', 2.0, 'Digital Services', 'Development'),
        ('SaaS', 2.0, 'Digital Services', 'SaaS'),
        ('Softwareentwicklung', 2.0, 'Digital Services', 'Development'),
        ('Compliance', 2.0, 'Finance Performance', 'GRC'),
        ('Enterprise', 2.0, 'Finance Performance', 'EPM'),
        ('Finance', 2.0, 'Finance Performance', 'Finance Transformation'),
        ('Performance', 2.0, 'Finance Performance', 'EPM'),
        ('Efficiency', 2.0, 'Future Product Creation', 'R&D Efficiency'),
        ('Lifecycle', 2.0, 'Future Product Creation', 'PLM'),
        ('Software', 2.0, 'Future Product Creation', 'SDV'),
        ('Systems', 2.0, 'Future Product Creation', 'Systems Engineering'),
        ('Vehicle', 2.0, 'Future Product Creation', 'SDV'),
        ('defined', 2.0, 'Future Product Creation', 'SDV'),
        ('Change', 2.0, 'Future of Work', 'Culture & Change'),
        ('Collaboration', 2.0, 'Future of Work', 'Collaboration'),
        ('Culture', 2.0, 'Future of Work', 'Culture & Change'),
        ('Modern', 2.0, 'Future of Work', 'Collaboration'),
        ('New', 2.0, 'Future of Work', 'New Work Strategy'),
        ('Work', 2.0, 'Future of Work', 'New Work Strategy'),
        ('Workforce', 2.0, 'Future of Work', 'Workforce Transformation'),
        ('HR', 2.0, 'Human Capital', 'HR Transformation'),
        ('IT', 2.0, 'Human Capital', 'HR IT'),
        ('People', 2.0, 'Human Capital', 'People Analytics'),
        ('Solutions', 2.0, 'Human Capital', 'HR IT'),
        ('Talent', 2.0, 'Human Capital', 'Talent Management'),
        ('Access', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Advisory', 2.0, 'IT Strategy & Infrastructure', 'ITStrategy'),
        ('Architektur', 2.0, 'IT Strategy & Infrastructure', 'ITStrategy'),
        ('CIO', 2.0, 'IT Strategy & Infrastructure', 'ITStrategy'),
        ('Compliance', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Cybersecurity', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Digitalisierung', 2.0, 'IT Strategy & Infrastructure', 'Transformation'),
        ('HANA', 2.0, 'IT Strategy & Infrastructure', 'ERP'),
        ('ITIL', 2.0, 'IT Strategy & Infrastructure', 'ITOps'),
        ('ITSM', 2.0, 'IT Strategy & Infrastructure', 'ITOps'),
        ('Identity', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Infrastruktur', 2.0, 'IT Strategy & Infrastructure', 'ITStrategy'),
        ('Lizenzmanagement', 2.0, 'IT Strategy & Infrastructure', 'ITOps'),
        ('Migration', 2.0, 'IT Strategy & Infrastructure', 'ITStrategy'),
        ('Portfolio', 2.0, 'IT Strategy & Infrastructure', 'Management'),
        ('Rechenzentrum', 2.0, 'IT Strategy & Infrastructure', 'ITOps'),
        ('Schnittstellen', 2.0, 'IT Strategy & Infrastructure', 'Architecture'),
        ('Sicherheit', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Systemlandschaft', 2.0, 'IT Strategy & Infrastructure', 'Architecture'),
        ('Trust', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Zero', 2.0, 'IT Strategy & Infrastructure', 'Security'),
        ('Collaborative', 2.0, 'Industrial Data Ecosystems', 'Collaboration'),
        ('Data', 2.0, 'Industrial Data Ecosystems', 'Data Spaces'),
        ('Exchange', 2.0, 'Industrial Data Ecosystems', 'Data Exchange'),
        ('Processes', 2.0, 'Industrial Data Ecosystems', 'Collaboration'),
        ('Sovereignty', 2.0, 'Industrial Data Ecosystems', 'Data Exchange'),
        ('Spaces', 2.0, 'Industrial Data Ecosystems', 'Data Spaces'),
        ('Asset', 2.0, 'Industrial IoT', 'Asset Management'),
        ('Connected', 2.0, 'Industrial IoT', 'Connected Products'),
        ('Floor', 2.0, 'Industrial IoT', 'Shop Floor Integration'),
        ('Shop', 2.0, 'Industrial IoT', 'Shop Floor Integration'),
        ('AI', 2.0, 'Intelligent Automation', 'GenAI'),
        ('Analytics', 2.0, 'Intelligent Automation', 'Analytics'),
        ('Artificial', 2.0, 'Intelligent Automation', 'AI'),
        ('Automation', 2.0, 'Intelligent Automation', 'RPA'),
        ('Big', 2.0, 'Intelligent Automation', 'Data'),
        ('Celonis', 2.0, 'Intelligent Automation', 'Analytics'),
        ('Code', 2.0, 'Intelligent Automation', 'Low Code'),
        ('Data', 2.0, 'Intelligent Automation', 'Data'),
        ('Data', 2.0, 'Intelligent Automation', 'Analytics'),
        ('GenAI', 2.0, 'Intelligent Automation', 'GenAI'),
        ('Generative', 2.0, 'Intelligent Automation', 'GenAI'),
        ('Hyperautomation', 2.0, 'Intelligent Automation', 'Hyperautomation'),
        ('Intelligence', 2.0, 'Intelligent Automation', 'AI'),
        ('Intelligenz', 2.0, 'Intelligent Automation', 'General'),
        ('Künstliche', 2.0, 'Intelligent Automation', 'General'),
        ('Learning', 2.0, 'Intelligent Automation', 'AI'),
        ('Low', 2.0, 'Intelligent Automation', 'Low Code'),
        ('Machine', 2.0, 'Intelligent Automation', 'AI'),
        ('Mining', 2.0, 'Intelligent Automation', 'Process Mining'),
        ('Mining', 2.0, 'Intelligent Automation', 'Analytics'),
        ('Process', 2.0, 'Intelligent Automation', 'Analytics'),
        ('Process', 2.0, 'Intelligent Automation', 'RPA'),
        ('RPA', 2.0, 'Intelligent Automation', 'RPA'),
        ('Robotic', 2.0, 'Intelligent Automation', 'RPA'),
        ('AMS', 2.0, 'Managed Services', 'AMS'),
        ('Operations', 2.0, 'Managed Services', 'Cloud Operations'),
        ('Agile', 2.0, 'Management Consulting', 'General'),
        ('Change', 2.0, 'Management Consulting', 'Change Management'),
        ('Consulting', 2.0, 'Management Consulting', 'General'),
        ('Management', 2.0, 'Management Consulting', 'Change Management'),
        ('Management', 2.0, 'Management Consulting', 'General'),
        ('Organisationsentwicklung', 2.0, 'Management Consulting', 'Org Design'),
        ('Prozessberatung', 2.0, 'Management Consulting', 'General'),
        ('SAFe', 2.0, 'Management Consulting', 'General'),
        ('Scrum', 2.0, 'Management Consulting', 'General'),
        ('Strategieberatung', 2.0, 'Management Consulting', 'General'),
        ('Transformation', 2.0, 'Management Consulting', 'Transformation'),
        ('City', 2.0, 'Mobility', 'Smart City'),
        ('Fleet', 2.0, 'Mobility', 'Fleet Management'),
        ('MaaS', 2.0, 'Mobility', 'MaaS'),
        ('Agilität', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Backlog', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Coach', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Design', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Facilitation', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Governance', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Jira', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Kanban', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Lean', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Master', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Mindset', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Moderation', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('OKR', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Owner', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Planning', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Product', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('RTE', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Refinement', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Release', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Retrospektive', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Skalierung', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Sprint', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Story', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Thinking', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('User', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Wertstrom', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Workshop', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Agile', 2.0, 'Organizational Transformation', 'Agile Transformation'),
        ('Corporate', 2.0, 'Organizational Transformation', 'Corporate Strategy'),
        ('Anforderungen', 2.0, 'Project- & Delivery Management', 'Engineering'),
        ('Bericht', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Budget', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Dokumentation', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Engineering', 2.0, 'Project- & Delivery Management', 'Engineering'),
        ('Meilenstein', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('PMO', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Programm', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Projekt', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Qualität', 2.0, 'Project- & Delivery Management', 'Engineering'),
        ('Requirements', 2.0, 'Project- & Delivery Management', 'Engineering'),
        ('Risiko', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Risk', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Rollout', 2.0, 'Project- & Delivery Management', 'Delivery'),
        ('Test', 2.0, 'Project- & Delivery Management', 'Engineering'),
        ('4HANA', 2.0, 'SAP Transformation', 'S/4HANA'),
        ('Clean', 2.0, 'SAP Transformation', 'Clean Core'),
        ('Core', 2.0, 'SAP Transformation', 'Clean Core'),
        ('Roadmap', 2.0, 'SAP Transformation', 'S/4HANA'),
        ('SAP', 2.0, 'SAP Transformation', 'SAP Architecture'),
        ('27001', 2.0, 'Security', 'Compliance'),
        ('Access', 2.0, 'Security', 'IAM'),
        ('Cyber', 2.0, 'Security', 'General'),
        ('IAM', 2.0, 'Security', 'IAM'),
        ('ISO', 2.0, 'Security', 'Compliance'),
        ('IT', 2.0, 'Security', 'General'),
        ('Identity', 2.0, 'Security', 'IAM'),
        ('Management', 2.0, 'Security', 'IAM'),
        ('Operations', 2.0, 'Security', 'Ops'),
        ('Security', 2.0, 'Security', 'General'),
        ('Security', 2.0, 'Security', 'Ops'),
        ('Sicherheit', 2.0, 'Security', 'General'),
        ('TISAX', 2.0, 'Security', 'Automotive Security'),
        ('UX', 2.0, 'Security', 'General'),
        ('Chain', 2.0, 'Supply Chain & Operations', 'SC Strategy'),
        ('Procurement', 2.0, 'Supply Chain & Operations', 'Procurement'),
        ('Supply', 2.0, 'Supply Chain & Operations', 'SC Strategy'),
        ('Circular', 2.0, 'Sustainability', 'Circular Economy'),
        ('ESG', 2.0, 'Sustainability', 'ESG'),
        ('Economy', 2.0, 'Sustainability', 'Circular Economy'),
        ('Green', 2.0, 'Sustainability', 'Green IT'),
        ('Reporting', 2.0, 'Sustainability', 'ESG'),
        ('Sustainable', 2.0, 'Sustainability', 'Sustainable SC'),
        ('4HANA', 2.0, 'System Integration', 'SAP S/4HANA'),
        ('ABAP', 2.0, 'System Integration', 'SAP Development'),
        ('Analytics', 2.0, 'System Integration', 'SAP Analytics'),
        ('Ariba', 2.0, 'System Integration', 'SAP Procurement'),
        ('BTP', 2.0, 'System Integration', 'SAP BTP'),
        ('CX', 2.0, 'System Integration', 'SAP CX'),
        ('Cloud', 2.0, 'System Integration', 'SAP Cloud'),
        ('EWM', 2.0, 'System Integration', 'SAP Logistics'),
        ('Fiori', 2.0, 'System Integration', 'SAP UX'),
        ('SAP', 2.0, 'System Integration', 'SAP Cloud'),
        ('SAP', 2.0, 'System Integration', 'SAP CX'),
        ('SAP', 2.0, 'System Integration', 'SAP BTP'),
        ('SAP', 2.0, 'System Integration', 'SAP Logistics'),
        ('SAP', 2.0, 'System Integration', 'SAP HR'),
        ('SAP', 2.0, 'System Integration', 'SAP Procurement'),
        ('SAP', 2.0, 'System Integration', 'General'),
        ('SAP', 2.0, 'System Integration', 'SAP Analytics'),
        ('SuccessFactors', 2.0, 'System Integration', 'SAP HR'),
        ('TM', 2.0, 'System Integration', 'SAP Logistics'),
    ]

    # 3. EXCLUSIONS (Negative Criteria)
    exclusions = [
        ('Abwasser', -2.0, 'Ausschluss', 'Exclusion', 'Umwelt'),
        ('Arznei', -2.0, 'Ausschluss', 'Exclusion', 'Pharma'),
        ('Baugrund', -2.0, 'Ausschluss', 'Exclusion', 'Bauwesen'),
        ('Dach', -2.0, 'Ausschluss', 'Exclusion', 'Handwerk'),
        ('Druck', -2.0, 'Ausschluss', 'Exclusion', 'Büro'),
        ('Elektro', -2.0, 'Ausschluss', 'Exclusion', 'Handwerk'),
        ('Entsorgung', -2.0, 'Ausschluss', 'Exclusion', 'Umwelt'),
        ('Fahrzeug', -2.0, 'Ausschluss', 'Exclusion', 'Logistik'),
        ('Fliese', -2.0, 'Ausschluss', 'Exclusion', 'Handwerk'),
        ('Gebäude', -2.0, 'Ausschluss', 'Exclusion', 'Facility'),
        ('Gerüst', -2.0, 'Ausschluss', 'Exclusion', 'Bauwesen'),
        ('Handwerk', -2.0, 'Ausschluss', 'Exclusion', 'Handwerk'),
        ('Hardware', -2.0, 'Ausschluss', 'Exclusion', 'IT-Hardware'),
        ('Hochbau', -2.0, 'Ausschluss', 'Exclusion', 'Bauwesen'),
        ('Installation', -2.0, 'Ausschluss', 'Exclusion', 'Handwerk'),
        ('Instandhaltung', -2.0, 'Ausschluss', 'Exclusion', 'Service'),
        ('Kabel', -2.0, 'Ausschluss', 'Exclusion', 'IT-Hardware'),
        ('Kita', -2.0, 'Ausschluss', 'Exclusion', 'General'),
        ('LKW', -2.0, 'Ausschluss', 'Exclusion', 'Logistik'),
        ('Labor', -2.0, 'Ausschluss', 'Exclusion', 'Medizin'),
        ('Leistung', -2.0, 'Ausschluss', 'Exclusion', 'Bauwesen'),
        ('Maler', -2.0, 'Ausschluss', 'Exclusion', 'Handwerk'),
        ('Medizin', -2.0, 'Ausschluss', 'Exclusion', 'Medizin'),
        ('Mittel', -2.0, 'Ausschluss', 'Exclusion', 'Kontext'),
        ('Montage', -2.0, 'Ausschluss', 'Exclusion', 'Industrie'),
        ('Möbel', -2.0, 'Ausschluss', 'Exclusion', 'Büro'),
        ('Müll', -2.0, 'Ausschluss', 'Exclusion', 'Umwelt'),
        ('Post', -2.0, 'Ausschluss', 'Exclusion', 'Logistik'),
        ('Reparatur', -2.0, 'Ausschluss', 'Exclusion', 'Service'),
        ('Sanierung', -2.0, 'Ausschluss', 'Exclusion', 'Bauwesen'),
        ('Schiff', -2.0, 'Ausschluss', 'Exclusion', 'Logistik'),
        ('Transport', -2.0, 'Ausschluss', 'Exclusion', 'Logistik'),
        ('Vermessung', -2.0, 'Ausschluss', 'Exclusion', 'Bauwesen'),
        ('Wachschutz', -2.0, 'Ausschluss', 'Exclusion', 'Facility'),
        ('Winterdienst', -2.0, 'Ausschluss', 'Exclusion', 'Facility'),
        ('Catering', -5.0, 'Catering', 'Exclusion', 'Services'),
        ('Catering', -2.0, 'Catering', 'Exclusion', 'Services'),
        ('Kantine', -5.0, 'Catering', 'Exclusion', 'Services'),
        ('Kantine', -2.0, 'Catering', 'Exclusion', 'Services'),
        ('Bau', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Bauarbeiten', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Bauarbeiten', -5.0, 'Construction', 'Exclusion', 'General'),
        ('Dacharbeiten', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Dacharbeiten', -5.0, 'Construction', 'Exclusion', 'General'),
        ('Malerarbeiten', -5.0, 'Construction', 'Exclusion', 'General'),
        ('Malerarbeiten', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Rohbau', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Rohbau', -5.0, 'Construction', 'Exclusion', 'General'),
        ('Sanitär', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Sanitär', -5.0, 'Construction', 'Exclusion', 'General'),
        ('Tiefbau', -5.0, 'Construction', 'Exclusion', 'General'),
        ('Tiefbau', -2.0, 'Construction', 'Exclusion', 'General'),
        ('Gebäudereinigung', -2.0, 'Facility Management', 'Exclusion', 'General'),
        ('Gebäudereinigung', -5.0, 'Facility Management', 'Exclusion', 'General'),
        ('Hausmeister', -2.0, 'Facility Management', 'Exclusion', 'General'),
        ('Hausmeister', -5.0, 'Facility Management', 'Exclusion', 'General'),
        ('Reinigung', -2.0, 'Facility Management', 'Exclusion', 'General'),
        ('Reinigung', -5.0, 'Facility Management', 'Exclusion', 'General'),
        ('Büromöbel', -5.0, 'Furniture', 'Exclusion', 'Office'),
        ('Büromöbel', -2.0, 'Furniture', 'Exclusion', 'Office'),
        ('Drucker', -2.0, 'Hardware', 'Exclusion', 'Peripherals'),
        ('Lieferung', -2.0, 'Hardware', 'Exclusion', 'IT-Hardware'),
        ('Lieferung-von-PC', -2.0, 'Hardware', 'Exclusion', 'IT-Hardware'),
        ('PC', -2.0, 'Hardware', 'Exclusion', 'IT-Hardware'),
        ('Toner', -2.0, 'Hardware', 'Exclusion', 'Consumables'),
        ('Toner', -3.0, 'Hardware', 'Exclusion', 'Consumables'),
        ('von', -2.0, 'Hardware', 'Exclusion', 'IT-Hardware'),
        ('Sicherheitsdienst', -2.0, 'Security Services', 'Exclusion', 'Physical Security'),
        ('Sicherheitsdienst', -5.0, 'Security Services', 'Exclusion', 'Physical Security'),
    ]

    initial_keywords = []
    
    # Process Sectors
    for term, weight, subtype, subcat2, category in sectors:
        initial_keywords.append(KeywordCreate(
            term=term, 
            weight=weight, 
            category=category, 
            type="Sector", 
            sub_type=subtype,
            sub_category=subcat2
        ))

    # Process Services
    for term, weight, subtype, subcat in services:
        initial_keywords.append(KeywordCreate(
            term=term, 
            weight=weight, 
            category=subtype,
            type="Service", 
            sub_type=subtype,
            sub_category=subcat
        ))
        
    # Process Exclusions
    for term, weight, subtype, type_, subcat in exclusions:
         initial_keywords.append(KeywordCreate(
            term=term, 
            weight=weight, 
            category=subtype,
            type="Exclusion", 
            sub_type=subtype,
            sub_category=subcat
        ))

    return initial_keywords
