import pytest
import os
import uvicorn
import time
from multiprocessing import Process
from pact import Verifier
from main import app
from core.database import db
from models.orm import KeywordORM

# ──────────────────────────────────────────────────────────────
#  Provider Setup (Rating MS)
# ──────────────────────────────────────────────────────────────

def run_server():
    """Run the Rating MS for Pact verification."""
    os.environ["DATABASE_URL"] = "sqlite:///test_pact_rating.db"
    uvicorn.run(app, host="127.0.0.1", port=8013)

@pytest.fixture(scope="session", autouse=True)
def provider_server():
    """Lifecycle fixture for the provider server."""
    proc = Process(target=run_server, daemon=True)
    proc.start()
    time.sleep(2)  # Wait for startup
    yield
    proc.terminate()

# ──────────────────────────────────────────────────────────────
#  State Handlers
# ──────────────────────────────────────────────────────────────

@app.post("/_pact/provider-states")
async def provider_states(mapping: dict):
    """Seed data for Pact states."""
    state = mapping.get("state")
    if state == "keywords exist in the database":
        async with db.session_factory() as session:
            async with session.begin():
                # Clear and add a test keyword
                from sqlalchemy import delete
                await session.execute(delete(KeywordORM))
                kw = KeywordORM(
                    term="software",
                    weight=10.0,
                    type="Sector",
                    category="Sector"
                )
                session.add(kw)
    return {"status": "success"}

# ──────────────────────────────────────────────────────────────
#  Verification
# ──────────────────────────────────────────────────────────────

def test_rating_provider_honors_pact():
    """Verifies that Rating MS complies with the Enriching MS contract."""
    verifier = Verifier(
        provider='RatingMS',
        provider_base_url='http://127.0.0.1:8013'
    )
    
    # Path to the pact file generated by the consumer
    pact_file = os.path.join(os.getcwd(), "enriching", "pacts", "enrichingms-ratingms.json")
    
    # Add source and transport
    verifier.add_source(pact_file)
    verifier.add_transport("http", "127.0.0.1", port=8013)
    
    try:
        success, logs = verifier.verify(
            provider_states_setup_url="http://127.0.0.1:8013/_pact/provider-states"
        )
        assert success == 0
    except Exception as e:
        print("\n❌ PACT VERIFICATION FAILED")
        print(f"Error: {e}")
        # Re-raise to ensure pytest shows the failure
        raise
